### PR TITLE
Fix the error when clicking Settings examples

### PR DESCRIPTION
**Pull request by MurtadhaS**
A crash happens when popping from empty fragments stack in the SettingsExampleFragment.java

### CODE REVIEW

**Comment by MurtadhaS** [comment]
I signed it!

**Comment by dakegu** [comment]
looks like you checked in too many not needed files

**Comment by MurtadhaS** [comment]
Sorry. Should I do something about that ?

**Comment by dakegu** [comment]
if you dont know how to push another commit,  you can create a new pullrequest

**Comment by MurtadhaS** [comment]
couldn't it be merged in this current state?

**Comment by WeiHsinChen** [comment]
You only need to commit the files you modify. Others like Gradle and .idea files are not needed to be added to the repository.

**Comment by MurtadhaS** [comment]
Okay I will close this and do another pull request.

**Pull request closed without merging**
