### PR TITLE
Create a Demo to show how to build live TV channel apps for Android TV

### PR DESCRIPTION
**Pull request by meisen45**
Creating a TV input service to show how to build live TV channel apps for Android TV using the TV Input Framework (TIF) based on ExoPlayer2.

### CODE REVIEW

**Comment by meisen45** [comment]
I signed it!

**Comment by dakegu2** [comment]
I signed it!

**Review by Makibinyane — APPROVED** [review]

**Comment by jitesh903** [comment]
Muje live tv application banane ke liye kya karna padega.
Kya muje tv channel valo se permission leni padegi or pay karna padega.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Pull request closed without merging**
